{{ config(materialized='view') }}

SELECT CUSTOMER_ID,UPPER(TRIM(CUSTOMER_NAME)) AS CUSTOMER_NAME, LOWER(TRIM(EMAIL)) AS EMAIL, CITY, CURRENT_TIMESTAMP() AS DBT_LOAD_TS 
FROM {{ source('insurance_curated','DIM_CUSTOMER') }}

WHERE IS_CURRENT='Y'